name: Node 1 CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: lpodkalicki/avr-toolchain
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Listing all files in cloned repository
        run: ls -la
      - name: Building Node 1 firmware
        run: cd node1 && make
      - name: Archive Node 1 Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Saving firmware artifacts
          path: |
            node1/build/main.hex